### ISSUE TITLE
БЭМ, компонентность

### ISSUE THREAD

**Issue by EvgeniyChuprov** [iatsdotfatr/2nd-task#3]
Миксы запрещены стандартами.
![Снимок экрана от 2019-12-02 14-08-32](https://user-images.githubusercontent.com/36810364/69954812-44211b80-150d-11ea-9828-3c034947d025.png)
Почему модификатор блока снаружи блока?
![Снимок экрана от 2019-12-02 14-05-24](https://user-images.githubusercontent.com/36810364/69954649-d7a61c80-150c-11ea-9ec0-0041199a581a.png)
Проверить по всему проекту.

**Comment by EvgeniyChuprov** [comment]
Структура должна быть древовидная. В корне страницы один блок в который передаются все параметры. Этот блок содержит в себе блоки помельче и передает в них необходимые параметры, те в свою очередь в свои блоки  и так далее.

Пример:
 Страница landing в body подключает миксин landing передает в него параметры, а уже внутри миксина landing расположены все остальные подключенные блоки.  

Вообщем нужно реализовать компонентный подход как в реакте, но на миксинах.

Зачем эти элементы?
![Снимок экрана от 2019-12-05 11-46-54](https://user-images.githubusercontent.com/36810364/70218919-fc8cd080-1754-11ea-8ee9-04d5616bf278.png)

миксы убрать:
![Снимок экрана от 2019-12-05 11-50-56](https://user-images.githubusercontent.com/36810364/70219245-863c9e00-1755-11ea-8140-ec5c65698b59.png)
![Снимок экрана от 2019-12-05 11-51-35](https://user-images.githubusercontent.com/36810364/70219284-9c4a5e80-1755-11ea-937a-bd211f67808e.png)
![Снимок экрана от 2019-12-05 11-52-12](https://user-images.githubusercontent.com/36810364/70219335-b5530f80-1755-11ea-9738-5754cb80415e.png)
Эти что сразу в глаза бросились. По проекту еще думаю еще много.

**Comment by iatsdotfatr** [comment]
Класс .card это общие стили для всех карточек, удалить его и прописать в каждой карточке отдельно? Про .text тот же вопрос.

**Comment by EvgeniyChuprov** [comment]
Каждый блок самодостаточен 
![image](https://user-images.githubusercontent.com/36810364/70317731-64afe500-182f-11ea-9664-4879f7c5e05c.png)

**Comment by EvgeniyChuprov** [comment]
Инклюдить все подключаемые миксины.   
![Снимок экрана от 2019-12-10 13-35-16](https://user-images.githubusercontent.com/36810364/70522345-ff6f3300-1b51-11ea-8633-979f8db94065.png)
