### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by EvgeniyChuprov** [iatsdotfatr/2nd-task#4]
Переписать js на классы ES6.
Код должен соответствовать стандартам fsd и стайлгайду AirBnB, в том числе и по оформлению. Никаких var, ++ и так далее. Лучше поставить ESlint и настроить его на правила AirBnB.

**Comment by iatsdotfatr** [comment]
Инициализировать классы можно в тех же файлах, где они объявлены?

**Comment by EvgeniyChuprov** [comment]
1. Конструктор класса должен быть максимально легковесным;
2. Приватные методы обозначать _, сначала объявлять публичные методы, после приватные.
3. Все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-

**Comment by iatsdotfatr** [comment]
> Приватные методы обозначать _, сначала объявлять публичные методы, после приватные.

Есть ли конкретные инструкции, когда метод делать приватным, а когда нет? Я писал этот вопрос в общем чате четвертого задания, ответа не получил. Если пользоваться этими инструкциями:
![1](https://user-images.githubusercontent.com/51824674/70524010-dca34580-1b76-11ea-9edf-7d9328150b77.png)
то я могу все почти все методы из четвертого задания сделать приватными, а поскольку приватные методы не должны тестироваться, то тестов почти не будет. И в интернете много статей, говорящих о том, что приватные методы почти всегда признак плохого кода.

> Все классы, которые используем для поиска по DOM-у должны начинаться с префикса js-

В требованиях про это написано в разделе jQuery, для js querySelector это тоже применять?

**Comment by EvgeniyChuprov** [comment]
Если по простому, то если метод используется вне класса тогда он публичный в остальных случаях приватный.
Тестирование приватных методов осуществляется через публичные.
Пример: в публичный метод передаешь какие - то значения, во внутренних методах происходят какие то вычисления, второй публичный метод возвращает результат. Вот и сравниваешь соответствие переданных данных к полученному результату.
По поводу префикса js- применяется как и написано в стандартах 
![image](https://user-images.githubusercontent.com/36810364/70550324-9f46b400-1b86-11ea-8bae-fcf3fec76733.png)
Т.е.  для любого доступа к DOM элементам. Его лучше ставить к блоку, а скрипт уже смотрит через этот класс, как и что делать с элементами.

**Comment by EvgeniyChuprov** [comment]
Все js файлы должны быть на классах.
![Снимок экрана от 2019-12-12 16-28-13](https://user-images.githubusercontent.com/36810364/70715970-6fb9b800-1cfc-11ea-82a2-9ab6d7b15cdf.png)

**Comment by EvgeniyChuprov** [comment]
Часть js файлов по прежнему выполнена в функциональном стиле.

Методы можно вынести в отдельный метод и его использовать в конструкторе. 
![Снимок экрана от 2019-12-14 12-15-30](https://user-images.githubusercontent.com/36810364/70846562-79156280-1e6b-11ea-93f0-9d6a679d09f2.png)

**Comment by iatsdotfatr** [comment]
> Часть js файлов по прежнему выполнена в функциональном стиле.

Это про функцию в rangeslider.js?

**Comment by EvgeniyChuprov** [comment]
datepicker, pagination, textfield__input_masked.js (почему такое название?), ну и rangeslider.js

**Comment by iatsdotfatr** [comment]
В этих файлах выполняется инициализация сторонних плагинов согласно их документации. Какую логику должны реализовывать классы?

**Comment by EvgeniyChuprov** [comment]
Класс содержит в себе плагин и осуществляет его инициализацию, при необходимости может расширить функционал. Понятно описал?)
