### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by EvgeniyChuprov** [iatsdotfatr/2nd-task#5]
Данные полученные миксином нужно деструктуризировать, что б в начале файла было видно переменные полученные в объекте.
![Снимок экрана от 2019-12-06 14-27-33](https://user-images.githubusercontent.com/36810364/70320015-be66de00-1834-11ea-8911-378176f90262.png)

**Comment by EvgeniyChuprov** [comment]
Параметры в checkbox должны приходить из checkset. Для всех остальных миксинов точно также.

![Снимок экрана от 2019-12-17 13-54-51](https://user-images.githubusercontent.com/36810364/70989524-d8c27680-20d4-11ea-937d-254b7ce44908.png)

**Comment by iatsdotfatr** [comment]
В uikit тоже? Там будет больше сотни переменных, записанных в одну строку, потому что pug не поддерживает многострочную деструктуризацию.

**Comment by EvgeniyChuprov** [comment]
На вход миксина передаешь объект параметров и все. Какие сотни переменных? Или я тебя не понял. Представь, что все данные прилетают с сервера, страница получает объект и раскидывает его по своим элементам.
 
![Снимок экрана от 2019-12-18 15-37-51](https://user-images.githubusercontent.com/36810364/71087104-69b85100-21ac-11ea-914f-1e10e8bcf8b0.png)

**Comment by iatsdotfatr** [comment]
Я не про вызов миксина.
> 
> 
> Данные полученные миксином нужно деструктуризировать, что б в начале файла было видно переменные полученные в объекте.
> ![Снимок экрана от 2019-12-06 14-27-33](https://user-images.githubusercontent.com/36810364/70320015-be66de00-1834-11ea-8911-378176f90262.png)

Наверное, я вот эту фразу не так не понял. Как должно выглядеть объявление миксина? Так, или нет:
![m](https://user-images.githubusercontent.com/51824674/71169038-9c387b80-228a-11ea-9a0a-2baa200149fe.png)

**Comment by EvgeniyChuprov** [comment]
В миксин передаешь объектом, а в самом миксине разбираешь полученный объект на составляющие и передаешь их дальше.
Небольшой пример. Сверху пример миксина подключенного где то в другом файле.
Ниже реализация самого миксина.
![Снимок экрана от 2019-12-20 11-19-17](https://user-images.githubusercontent.com/36810364/71240597-9e4a1b00-231a-11ea-8950-335dcac96945.png)
