### ISSUE TITLE
pixel perfect

### ISSUE THREAD

**Issue by EvgeniyChuprov** [iatsdotfatr/2nd-task#6]
Поправить везде заголовки.
![Снимок экрана от 2019-12-14 11-27-02](https://user-images.githubusercontent.com/36810364/70845970-c0005980-1e65-11ea-857d-23f59180080b.png)

![Снимок экрана от 2019-12-14 11-27-52](https://user-images.githubusercontent.com/36810364/70845991-f0e08e80-1e65-11ea-8662-96e008760867.png)
 На лендинге
![Снимок экрана от 2019-12-14 11-39-04](https://user-images.githubusercontent.com/36810364/70846044-6e0c0380-1e66-11ea-933e-82e84b773883.png)

**Comment by iatsdotfatr** [comment]
В лендинге текст уходит на 6 пикселей за контейнер, раньше там стоял "margin: -6px". Выровнять через "position: absolute"?

Заголовок при наложении у меня выглядит вот так:
![px](https://user-images.githubusercontent.com/51824674/70848991-9f5af280-1eab-11ea-9da8-a6eba574066a.png)

Нижний ряд слайдеров вот так:
![px1](https://user-images.githubusercontent.com/51824674/70849032-ddf0ad00-1eab-11ea-9e55-85bb40fa32d3.png)
Номера совпадают, цена и отзывы плывут, но в uikit совпадают полностью.

Наверное, надо накладывать одни и те же файлы.

**Comment by EvgeniyChuprov** [comment]
> В лендинге текст уходит на 6 пикселей за контейнер, раньше там стоял "margin: -6px". Выровнять через "position: absolute"?

 Не использовать position absolute для стилизации, где это можно заменить другими подходами;
Не проще будет расширить landing__container тогда текст снизу встанет на место, а landing__find добавить отступ слева?
