### ISSUE TITLE
Небольшие финальные замечания

### ISSUE THREAD

**Issue by Sergio-Ka** [iatsdotfatr/2nd-task#7]
1. Импорты должны быть в самом верху файла, это улучшает читаемость и сразу видны зависимости компоненты. В папке src/pug/pages во всех файлах это правило не соблюдается.
2. Именование хендлеров должно быть вида handle[ElementName]EventName вместо _datedropdownHandler(event) (тут для примера, вообще они должны именоваться во всем проекте однообразно).
3. Необходимо избегать сокращений в именованиях, так как сокращение которое очевидно одному, может быть не очевидно другому типа dropdown__expand-btn, .d-footer__descr #{descr}. Посмотреть во всем проекте.
4. Отдавать предпочтение нативным методам массивов вместо for. Например radiosetHandler(event) {
    for (let i = 0; i < this.radios.length; i += 1) {
тут можно использовать forEach. Посмотреть по всему проекту.

**Comment by iatsdotfatr** [comment]
> Импорты должны быть в самом верху файла, это улучшает читаемость и сразу видны зависимости компоненты. В папке src/pug/pages во всех файлах это правило не соблюдается.

Если есть extends, то на самый верх не получится:

![import](https://user-images.githubusercontent.com/51824674/72778478-b085e480-3c4b-11ea-8f79-cd30e4f24770.png)

Сделал на строку ниже.

**Comment by Sergio-Ka** [comment]
Ну ок, я подозревал, что там с этим могут быть заморочки, тогда оставляем так.
